### ISSUE TITLE
白名单有没有办法在维护维护，我觉得挺好用，就是规则少了

### ISSUE THREAD

**Issue by z273703837** [viosey/gfw_whitelist#1]
试了下白名单感觉是好用不少，但是规则少了，能多加点么

**Comment by Omico** [comment]
你也可以作为贡献者帮助我们完善这份规则

**Comment by neoFelhz** [comment]
Repository 里已经提供了一整套便利可靠的工具来帮助你完善这份列表，包括一套 java 编写成的 Cli 工具和一套规范你的提交的 shell 脚本。README.md 内有工具的详细使用教程。我们对符合规范的 Pull Request 表示欢迎。

**Comment by neoFelhz** [comment]
如果没有别的什么疑问，我就 close 这条没有意义的 issue 了。如果还有任何疑问，欢迎继续提问。
