### ISSUE TITLE
Academic Websites

### ISSUE THREAD

**Issue by kurikomoe** [viosey/gfw_whitelist#11]
Academic websites shouldn't be visited through proxy because they often judge the visitor by their ip.

*.acs.org
*.rsc.org
*.sciencemag.org
*.nature.com
*.aps.org
*.webofknowledge.com
*.ieee.org
*.sciencedirect.com
*.cnki.net

**Comment by neoFelhz** [comment]
We will add those domains from the list.

**Comment by Omico** [comment]
Add in https://github.com/neko-dev/gfw_whitelist/commit/5b586b8f47882fd5cffe0c3b2c44b53ba344129c
