### ISSUE TITLE
想请问下，如何将一个网址所有的内容通过代理进行访问，需要如何设置？

### ISSUE THREAD

**Issue by z273703837** [viosey/gfw_whitelist#2]
我想访问一个网址，如果只是添加进去也是可以访问，但是我经常通过脚本从该网站上下载文件，在下载过程中并没有通过代理连接，我想要全局进行连接怎么处理？

**Comment by kmahyyg** [comment]
@z273703837 使用proxifier将脚本的解析器(eg.     cmd pythom添加到proxied list.
