### ISSUE TITLE
Google search URL wrong match

### ISSUE THREAD

**Issue by chrisxiha** [viosey/gfw_whitelist#22]
When Google searching domains in gfw_whitelist, for example 

> edu.cn

 it will open URL: [https://www.google.com/search?q=edu.cn](https://www.google.com/search?q=edu.cn), which matches current whitelist rules though it shouldn't.

Sorry I'm not familiar with AutoProxy rules, anything to fix this?

**Comment by aglent** [comment]
you can add a line
@@||google.com
