### ISSUE TITLE
Clean up the list 整理一下清单

### ISSUE THREAD

**Issue by Prurite** [viosey/gfw_whitelist#33]
是所有服务器设在大陆的网站都可以被加入清单，还是定为【访问量大的，经过代理访问缓慢的，网站本身特性要求直连的，耗费流量较多的】四类才入清单？

**Comment by cubesky** [comment]
经过代理访问缓慢的 和 网站本身特性要求直连的 才加入清单

**Comment by Prurite** [comment]
那是不是可以考虑一下清理一下单子

**Comment by Prurite** [comment]
或者弄一个 tiny_list 和 full_list 这样？full_list 就是收集到的所有 ip 在大陆的网站， tiny_list 就只是常用域名列表（访问缓慢的，国内大厂网站，视频网站，在线商店，对地区有要求的，etc）

**Comment by Omico** [comment]
@cubesky 已经说的很清楚了 `经过代理访问缓慢的 和 网站本身特性要求直连的 才加入清单`
所以无需分为 `tiny_list` 和 `full_list`。
不过，清理清单是需要的，欢迎提交删减。

**Comment by Prurite** [comment]
一些国内的著名网站也需要设置白名单的吧…… 比如很多有异地登陆保护那种，和百毒那种（网上不是都流传过一篇根据进出境流量特性判断代理的文章吗，如果使用代理访问国内ip的网站**可能**导致代理被封锁可能性增大

**Comment by cubesky** [comment]
@Prurite 这个不是此列表解决的问题
